export interface BurialRecord {
    id: number,
    squarenorthsouth: string,
    headdirection: string,
    sex: "male" | "female",
    northsouth: number,
    depth: number,
    eastwest: number,
    adultsubadult: string,
    facebundles: boolean,
    southtohead: number,
    preservation: number,
    fieldbookpage: number,
    squareeastwest: string,
    goods: string,
    text: string,
    wrapping: string,
    haircolor: string,
    westtohead: number,
    samplescollected: string,
    area: string,
    burialid: string,
    length: number,
    burialnumber: number,
    dataexpertinitials: string,
    westtofeet: number,
    ageatdeath: string,
    southtofeet: number,
    excavationrecorder: string,
    photos: boolean,
    hair: string,
    burialmaterials: string,
    dateofexcavation: string,
    fieldbookexcavationyear: number,
    clusternumber: number,
    shaftnumber: number,
}